name: NetFrameWork.Legacy.CI

on: [push]
 
jobs:
  build:
    runs-on: shawngib/nano_customervoice_api

    steps:
    - uses: actions/checkout@v1
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore packages
      run: nuget restore contosouniversity
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build with MSBuild
      run: msbuild  YOUR_SOLUTION_NAME -p:Configuration=Release
